import 'package:meta/meta.dart';
import '../extensions/data_class_extensions.dart';
import '../tdapi.dart';

/// A file generated by the application
@immutable
class InputPeerUser extends InputPeer {
  const InputPeerUser({required this.userId, required this.accessHash});

  /// [originalPath] Local path to a file from which the file is generated; may
  /// be empty if there is no such file

  final int userId;
  final int accessHash;
  static const String constructor = 'inputPeerUser';

  static InputPeerUser? fromJson(Map<String, dynamic>? json) {
    if (json == null) {
      return null;
    }

    return InputPeerUser(
        userId: json['user_id'], accessHash: json['access_hash']);
  }

  @override
  String getConstructor() => constructor;

  @override
  Map<String, dynamic> toJson() => <String, dynamic>{
        'user_id': userId,
        'access_hash': accessHash,
        '@type': constructor,
      };

  @override
  bool operator ==(Object other) => overriddenEquality(other);

  @override
  int get hashCode => overriddenHashCode;
}
