version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
      - db
    ports:
      - 3000:5000
      - 9229:9229
    env_file:
      - .env
    volumes:
      - ./src:/app/src:ro
      - ./libs:/app/libs:ro
    links:
      - db
    
  db:
    image: mysql
    restart: always
    ports:
      - 3307:3306
    expose:
      - "3307"
    environment:
      MYSQL_DATABASE: lddb
      MYSQL_ROOT_PASSWORD: test
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: root
      MYSQL_HOST: localhost
    command: --default-authentication-plugin=mysql_native_password  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    cap_add:
      - SYS_NICE
    volumes:
      - ./database/lddb:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

